site_name: The Tiny Marmalade Game
site_url: https://jtech-labs.github.io/TheTinyMarmaladeGame
repo_url: https://github.com/JTech-Labs/TheTinyMarmaladeGame
repo_name: TheTinyMarmaladeGame
docs_dir: docs
copyright: The Tiny Marmalade Game Documentation &copy 2025 by JTech-Labs is licensed under CC BY-NC-SA 4.0 

extra:
  alternate:
    - name: English
      link: en/
      lang: en
    - name: Español
      link: es/
      lang: es
# social:
#   - icon: fontawesome/brands/mastodon
#     link: https://fosstodon.org/example
#     name: Example on fosstodon

plugins:
  - search
  - offline

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  
  font:
    code: JetBrains Mono
    text: JetBrains Mono
  
  icon:
    repo: fontawesome/brands/git-alt

  logo: assets/ttm.png
  favicon: assets/ttm.png

  features:
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - navigation.footer
    - navigation.top

  palette:
      # Palette toggle for light mode
      - scheme: default
        primary: teal
        accent: cyan
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode

      # Palette toggle for dark mode
      - scheme: slate
        primary: teal
        accent: cyan
        toggle:
          icon: material/weather-night
          name: Switch to light mode

nav:
  - Home: en/index.md
  - Hello: en/hello.md

